name: telemetry-bridge CI

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: "Where to deploy"
        type: choice
        required: true
        options:
          - staging
          - production
      image_tag:
        description: "Image tag to deploy (default: commit SHA)"
        type: string
        required: false

# Least privilege for CI:
# - read repo contents
# - write packages only when pushing images (still governed by event conditions)
permissions:
  contents: read
  packages: write

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"
          cache: maven

      - name: Run tests
        run: mvn -B verify

  docker:
    name: Build & Push Docker image
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.out.outputs.image }}
      tag: ${{ steps.out.outputs.tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Compute tag
        id: vars
        shell: bash
        run: |
          set -euo pipefail

          # For workflow_dispatch you may optionally override the tag
          DISPATCH_TAG="${{ github.event.inputs.image_tag }}"
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "$DISPATCH_TAG" ]]; then
            echo "TAG=$DISPATCH_TAG" >> "$GITHUB_ENV"
          else
            echo "TAG=${{ github.sha }}" >> "$GITHUB_ENV"
          fi

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Export image ref
        id: out
        shell: bash
        run: |
          set -euo pipefail
          echo "image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> "$GITHUB_OUTPUT"
          echo "tag=${{ env.TAG }}" >> "$GITHUB_OUTPUT"
